name: Space CI
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
      uses: actions/checkout

      - name: Use Node
      uses: actions/setup-node
      with:
        node-version: '14'

      - name: Run ESLint
        run: yarn add lint

      - name: Run Prettier
        run: yarn add prettier
    
