name: Space CI
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout
      - uses: actions/setup-node
      with:
        node-version: '14'
      - run: yarn add lint
      - run: yarn add prettier
    
