name: Space CI
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout
      - name: Node
        uses: actions/setup-node
        with:
          node-version: '20.3.0'
      - name: Eslint
        run: yarn add lint
      - name: Prettier
        run: yarn add prettier
    
